* Dad’s sports car CC&R (conditions, rules and regulations)

- Phone use: no texting and driving.
- Destination: know where you go, set your navigation. You also need to report once reached it.
- Snow and rain: this car is equipped with extreme summer performance tires which do not work on wet and snow roads. In any case, let them warm up a bit and after 5 miles they will stick.
- GF/SO rule: when you have a passenger, never show off (which is a natural instinct it is good to be aware of). Let your GF read it too. We will check it.
- $100 security deposit: did I say to not show off, that should help to understand it .
- Parking: always park in sparse areas, preferably in reversed (nose in front) orientation. Best way to avoid door dings and it looks good too.
- No commute: this is only weekend car. Statistically most accidents happen within 10 miles from home.
- Cops: sports cars like this are cop magnets and you might be pulled “just because” – happened many times. Know your talk beforehand.
- Speed and travel lanes: speed is relative (It was the 16 year old Albert Einstein who first gave serious consideration to why this might be the case), so do not speed. 5MPH is over is fine, never hog left lane, use middle whenever possible.
- Mirrors: should be set out as far as possible. You should not see car edges unless you turn your head. There are motorcycles out there.
- Starting up and revving: after starting car, let it idle for 15 seconds and wait for blue light to go away before going above 4KRPM, never rev it up to red line with engine not under the load. It is also good to let engine run for a few seconds before you shut it down.
- Keys: keep them in the safe place, attached to something you do not want to lose.
